version: '3.8'

services:
  nest-app:
    build: .
    container_name: nest-app
    ports:
      - '3345:3344'
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules  
    env_file:
      - .env
    restart: unless-stopped
  db:
    image: postgres:13
    container_name: social-network-db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
